import { AlertProvider } from "~/AlertContext";
import "~/styles/globals.css";

import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";
import fonts from "~/styles/fonts";

export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
    minimumScale: 0.5,
    maximumScale: 2,
};

export const metadata: Metadata = {
  title: {
      default: "CBSH Deco My Tree",
      template: "%s | CBSH Deco My Tree"
  },
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.png" }],
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return <html lang="en" className="min-h-screen bg-gradient-to-r text-white from-[#b50f0f] to-[#f28b15]">
        <body className={ fonts.Torus.className + " select-none" }>
            <AlertProvider>{ children }</AlertProvider></body>
    </html>;
}